# Generated by Django 5.1 on 2024-09-07 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_remove_user_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='province',
        ),
    ]
